import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Condensed, Inter } from "next/font/google";
import "./globals.css";
import  Header  from "@/app/components/layouts/header";
import Image from "next/image";
import gradientImg from "@/public/images/gradient.webp"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotsoCondensed = Roboto_Condensed({
  variable: "--font-robotso-condensed",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Murunwa's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="container max-w-3xl mx-auto min-h-screen flex flex-col px-4 py-5">
        <div className="flex-1 w-full">
          <Header />
          {children}
        </div>
        {/* <Image
              className="absolute left-0 md:left-1/2 top-0 -z-10 -translate-x-1/2 lg:scale-100 object-cover w-full"
              src={gradientImg}
              role="presenation"
              alt="Gradient background"
              priority
            /> */}
      </div>
      </body>
    </html>
  );
}
